apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
      - name: podinfo
        image: stefanprodan/podinfo:6.14.1
        ports: 
        - containerPort: 9898
        envFrom:
        - configMapRef:
            name: podinfo-config
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: podinfo-auth
              key: api-key
        volumeMounts:
        - name: config
          mountPath: /etc/podinfo-config
      volumes:
      - name: config
        configMap:
          name: podinfo-config

